import Head from "next/head";
import { useContext } from "react";
import Main from "../components/Main";
import AuthContext from "../context/AuthContext";
import supabase from "../supabase/client";
import { useSelector } from "react-redux";
export default function Home({ data }) {
  const auth = useSelector((state) => state.auth.value);
  console.log(auth);
  const { theme } = useContext(AuthContext);
  // const session = useSession();
  // const user = useUser();
  async function userSession() {
    // console.log("SESSION<<<<", session);
  }
  userSession();
  return (
    <div>
      <Head>
        <title>Bikrant | Let's Blog Together</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main />
    </div>
  );
}
